# valor = 20.25892
# print(round(valor,3)) # diminuir o tamanho do numeros

# lista = [1,2,3,4,5,6]
# print (len(lista)) #listas []
# dicionario = {'nome': 'jose', 'idade':19, 'vip':True}
# print(len(dicionario))
 
# string = 'manipulando strings' 
# sub = string.replace('manipulando', 'python') # trocar o nome da variavel
# print(sub) 
# print(string + ' teste ') #adicionar valores
# print(string.count('i')) #contar quantas vezes aparece 
# print(string.upper()) # deixar tudo maiusculo 
# string1 ='reovendo espaço'
# print(string1.strip()) # remove tos os espaçoes que tem no inicio e no final(geralmente usado para reparação de erros)


# atividade 1

# palavra = input("digite uma palavra: ")
# print(palavra)
# print(len(palavra))
# divisao = len(palavra)/3
# print("A divisão é igual a:", divisao)
# print("o tamanho da palavra é igual a:", len(palavra))
# print("O valor arredondado e igual a:", round(divisao,2))

#atividade 1 

# string = ("maçã uva laranja abacate abacaxi limão")
# print(string.split())

nome = "Sarah Layane"
print(nome.upper())
print(nome.lower())
